version: '3.8'

services:
  translator-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUN_MODE=rest
      - WHISPER_COMPUTE_TYPE=float32
      - TRANSCRIPTION_MODE=hf
      - HF_TOKEN=hf_RgvZcCpTIXksIRnagbHpTOPtGRveQRfVn
      - PLAY_HT_USER_ID=N3FVIUVJ3id35XU4t5gPXsaBrUt2
      - PLAY_HT_API_KEY=86e1410f7aa247a281fb46a56ef744ad
      - POE_API_KEY=OZqAI-hJHPwACdPgnfKj1EM6Bf2K1snpSYOqEp-xVr0
      - ANTHROPIC_API_KEY=sk-ant-api03-Nug_3cFeix3W6o0uw6DB931iXRF0wufdu
    volumes:
      - ./mnt/data_bucket:/mnt/data_bucket 